#!/usr/bin/env python

import argparse
import getpass
import os
import sys
import time

import bs

# import gnupg
# gpg = gnupg.GPG('/usr/local/bin/gpg',
#                 homedir=os.path.join(os.environ.get('HOME'), '.gnupg'))


def btfu_add(args):
    # FIXME: right now `add` just rebuilds the entire root tree. It should be
    # able to add a single file and simply rebuild its parent branches.
    rootref = bs.get_rootref()
    treeref = bs.put_file('.')
    ls = [[bs.BS_TYPE_TREE, treeref]]
    if rootref is not None:
        root = bs.get_root(rootref)
        if root.get(bs.BS_TYPE_TREE, None) == treeref:
            print rootref
            return
    if rootref is not None:
        ls.append([bs.BS_TYPE_PARENT, rootref])
    ls.append([bs.BS_TYPE_CTIME, str(time.time())])
    rootref = bs.put_blob('\n'.join(' '.join(pair) for pair in ls))
    bs.set_rootref(rootref)
    print rootref


def btfu_get(args):
    print bs.get_blob(args.ref),


def btfu_init(args):
    bs.init()


def btfu_list(args):
    if args.ref is None:
        args.ref = bs.get_root()[bs.BS_TYPE_TREE]
    bs.index_build(args.ref)


def btfu_mount(args):
    try:
        import fs
        fs.mount(bs.get_root(args.rootref)[bs.BS_TYPE_TREE], args.mountpoint)
    except ImportError, e:
        print >>sys.stderr, 'error: mount requires additional libraries:', e


def btfu_put(args):
    if args.path is None:
        print bs.put_blob(sys.stdin.read())
    else:
        print bs.put_file(args.path)


def btfu_rootref(args):
    print bs.get_rootref()


def main(args):
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers()
    # add
    subparser = subparsers.add_parser('add')
    subparser.set_defaults(func=btfu_add)
    # get
    subparser = subparsers.add_parser('get')
    subparser.set_defaults(func=btfu_get)
    subparser.add_argument('ref')
    # init
    # TODO: make this automatic
    subparser = subparsers.add_parser('init')
    subparser.set_defaults(func=btfu_init)
    # list
    subparser = subparsers.add_parser('list')
    subparser.set_defaults(func=btfu_list)
    subparser.add_argument('ref', nargs='?')
    # mount
    subparser = subparsers.add_parser('mount')
    subparser.set_defaults(func=btfu_mount)
    subparser.add_argument('mountpoint')
    subparser.add_argument('treeref', nargs='?')
    # put
    subparser = subparsers.add_parser('put')
    subparser.set_defaults(func=btfu_put)
    subparser.add_argument('path', nargs='?')
    # rootref
    subparser = subparsers.add_parser('rootref')
    subparser.set_defaults(func=btfu_rootref)
    # ...
    args = parser.parse_args(args)
    func = args.func
    del args.func
    func(args)


if __name__ == '__main__':
    main(sys.argv[1:])
